# Generated by Django 2.2.2 on 2019-07-03 17:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('latitude', django_google_maps.fields.GeoLocationField(max_length=100)),
                ('longtitude', django_google_maps.fields.GeoLocationField(max_length=100)),
                ('house_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('INDEPENDENT', 'Independent')], default='APARTMENT', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('balcony', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField()),
                ('garage', models.IntegerField(default=0)),
                ('sqft', models.IntegerField()),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('video', models.FileField(blank=True, upload_to='videos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('water_supply', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('lawn', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('water_heater', models.BooleanField(default=False)),
                ('tile_type', models.CharField(choices=[('TILE', 'Tile'), ('MOSSAIC', 'Mossaic'), ('GRANITE', 'Granite'), ('MARBLE', 'Marble')], default='TILE', max_length=10)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Realtor')),
            ],
        ),
    ]
